# Generated by Django 3.1 on 2020-08-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activtyapp', '0003_auto_20200816_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='tz',
            field=models.CharField(blank=True, choices=[('Canada/Atlantic', 'Canada/Atlantic'), ('Canada/Central', 'Canada/Central'), ('Canada/Eastern', 'Canada/Eastern'), ('Canada/Mountain', 'Canada/Mountain'), ('Canada/Pacific', 'Canada/Pacific')], max_length=100, null=True, unique=True),
        ),
    ]
